package report;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.print.PrinterException;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class ReportGeneratorForm extends JPanel {
    private ReportGenerator reportGenerator;
    private JComboBox<InventoryReportType> reportTypeCombo;
    private JFormattedTextField startDateField;
    private JFormattedTextField endDateField;

    private JButton generateButton;
    private JButton printButton;
    private JButton exportButton;
    private JButton saveButton;
    private JButton loadButton;
    private JButton deleteButton;

    private JTextArea reportArea;

    private JTable reportsTable;
    private DefaultTableModel tableModel;
    private JLabel statusLabel;

    private int currentUserId;
    private String currentUserName;

    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    public ReportGeneratorForm(Connection connection, int userId, String userName) {
        this.currentUserId = userId;
        this.currentUserName = userName;
        this.reportGenerator = new ReportGenerator(connection);

        initComponents();
        layoutComponents();
        setupListeners();
        loadSavedReports();
    }

    private void initComponents() {
        // Report type selection
        reportTypeCombo = new JComboBox<>(InventoryReportType.values());

        // Date fields
        startDateField = new JFormattedTextField(DATE_FORMATTER);
        startDateField.setValue(LocalDate.now().minusDays(30));
        startDateField.setColumns(10);

        endDateField = new JFormattedTextField(DATE_FORMATTER);
        endDateField.setValue(LocalDate.now());
        endDateField.setColumns(10);

        // Buttons
        generateButton = new JButton("Generate Report");
        generateButton.setIcon(new ImageIcon(getClass().getResource("/icons/generate.png")));

        printButton = new JButton("Print");
        printButton.setIcon(new ImageIcon(getClass().getResource("/icons/print.png")));

        exportButton = new JButton("Export");
        exportButton.setIcon(new ImageIcon(getClass().getResource("/icons/export.png")));

        saveButton = new JButton("Save");
        saveButton.setIcon(new ImageIcon(getClass().getResource("/icons/save.png")));

        loadButton = new JButton("Load");
        loadButton.setIcon(new ImageIcon(getClass().getResource("/icons/load.png")));

        deleteButton = new JButton("Delete");
        deleteButton.setIcon(new ImageIcon(getClass().getResource("/icons/delete.png")));
        deleteButton.setEnabled(false);

        // Report display area
        reportArea = new JTextArea(20, 70);
        reportArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        reportArea.setEditable(false);

        // Reports table
        String[] columns = {"ID", "Title", "Type", "Date", "Generated By"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) return Integer.class;
                return String.class;
            }
        };

        reportsTable = new JTable(tableModel);
        reportsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        reportsTable.setRowHeight(25);
        reportsTable.getSelectionModel().addListSelectionListener(e -> {
            deleteButton.setEnabled(reportsTable.getSelectedRow() >= 0);
        });

        // Status label
        statusLabel = new JLabel("Ready");
        statusLabel.setBorder(BorderFactory.createLoweredBevelBorder());
    }

    private void layoutComponents() {
        setLayout(new BorderLayout(10, 10));
        setBorder(new EmptyBorder(10, 10, 10, 10));

        // Top panel: Controls
        JPanel controlPanel = new JPanel(new GridBagLayout());
        controlPanel.setBorder(new TitledBorder("Report Parameters"));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.fill = GridBagConstraints.HORIZONTAL;


        // Row 1: Report Type
        gbc.gridx = 0; gbc.gridy = 0;
        controlPanel.add(new JLabel("Report Type:"), gbc);

        gbc.gridx = 1; gbc.weightx = 1.0;
        controlPanel.add(reportTypeCombo, gbc);


        // Row 2: Date Range
        gbc.gridx = 0; gbc.gridy = 1;
        controlPanel.add(new JLabel("Start Date:"), gbc);

        gbc.gridx = 1;
        controlPanel.add(startDateField, gbc);

        gbc.gridx = 2; gbc.weightx = 0;
        controlPanel.add(new JLabel("End Date:"), gbc);

        gbc.gridx = 3; gbc.weightx = 1.0;
        controlPanel.add(endDateField, gbc);


        // Row 3: Generate Button
        gbc.gridx = 0; gbc.gridy = 2;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.NONE;
        gbc.anchor = GridBagConstraints.CENTER;
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 5));
        buttonPanel.add(generateButton);
        controlPanel.add(buttonPanel, gbc);

        add(controlPanel, BorderLayout.NORTH);

        // Center: Split pane with report area and saved reports
        JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT);
        splitPane.setResizeWeight(0.7);

        // Left: Report display
        JPanel reportPanel = new JPanel(new BorderLayout(5, 5));
        reportPanel.setBorder(new TitledBorder("Report Preview"));

        JScrollPane reportScroll = new JScrollPane(reportArea);
        reportScroll.setPreferredSize(new Dimension(500, 400));
        reportPanel.add(reportScroll, BorderLayout.CENTER);

        // Report action buttons
        JPanel reportActions = new JPanel(new FlowLayout(FlowLayout.LEFT));
        reportActions.add(printButton);
        reportActions.add(exportButton);
        reportActions.add(saveButton);
        reportPanel.add(reportActions, BorderLayout.SOUTH);

        // Right: Saved reports
        JPanel savedPanel = new JPanel(new BorderLayout(5, 5));
        savedPanel.setBorder(new TitledBorder("Saved Reports"));

        JScrollPane tableScroll = new JScrollPane(reportsTable);
        tableScroll.setPreferredSize(new Dimension(300, 400));
        savedPanel.add(tableScroll, BorderLayout.CENTER);

        // Saved reports actions
        JPanel savedActions = new JPanel(new FlowLayout(FlowLayout.LEFT));
        savedActions.add(loadButton);
        savedActions.add(deleteButton);
        savedPanel.add(savedActions, BorderLayout.SOUTH);

        splitPane.setLeftComponent(reportPanel);
        splitPane.setRightComponent(savedPanel);
        add(splitPane, BorderLayout.CENTER);

        // Bottom: Status bar
        add(statusLabel, BorderLayout.SOUTH);
    }

    private void setupListeners() {
        generateButton.addActionListener(e -> generateReport());
        printButton.addActionListener(e -> printReport());
        exportButton.addActionListener(e -> exportReport());
        saveButton.addActionListener(e -> saveCurrentReport());
        loadButton.addActionListener(e -> loadSelectedReport());
        deleteButton.addActionListener(e -> deleteSelectedReport());

        // Double-click to load report
        reportsTable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    loadSelectedReport();
                }
            }
        });
    }

    private void generateReport() {
        InventoryReportType reportType = (InventoryReportType) reportTypeCombo.getSelectedItem();
        LocalDate startDate = (LocalDate) startDateField.getValue();
        LocalDate endDate = (LocalDate) endDateField.getValue();

        // Validate dates
        if (startDate == null || endDate == null) {
            JOptionPane.showMessageDialog(this, "Please enter valid dates",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (startDate.isAfter(endDate)) {
            JOptionPane.showMessageDialog(this, "Start date must be before end date",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Show progress dialog for long operations
        ProgressDialog progress = new ProgressDialog(
                (Frame) SwingUtilities.getWindowAncestor(this),
                "Generating Report...");
        progress.setVisible(true);

        SwingWorker<Report, Void> worker = new SwingWorker<Report, Void>() {
            @Override
            protected Report doInBackground() throws Exception {
                try {
                    switch (reportType) {
                        case INVENTORY_SUMMARY:
                            return reportGenerator.generateInventorySummary(
                                    currentUserId);
                        case SALES_REPORT:
                            return reportGenerator.generateSalesReport(
                                    startDate, endDate, currentUserId);
                        case LOW_STOCK:
                            return reportGenerator.generateLowStockReport(
                                    currentUserId);
                        case TRANSACTION_HISTORY:
                            return reportGenerator.generateTransactionHistory(
                                    startDate, endDate, currentUserId);
                        case null:
                        default:
                            throw new IllegalArgumentException("Unsupported report type");
                    }
                } catch (Exception e) {
                    throw e;
                }
            }

            @Override
            protected void done() {
                progress.dispose();

                try {
                    Report report = get();
                    displayReport(report);
                    statusLabel.setText("Report generated successfully");

                    // Reload saved reports
                    loadSavedReports();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(ReportGeneratorForm.this,
                            "Error generating report: " + e.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                    statusLabel.setText("Error: " + e.getMessage());
                }
            }
        };

        worker.execute();
    }

    private void displayReport(Report report) {
        if (report == null) {
            reportArea.setText("No report data available");
            return;
        }

        StringBuilder display = new StringBuilder();
        display.append("REPORT ID: ").append(report.getReportId()).append("\n");
        display.append("TITLE: ").append(report.getTitle()).append("\n");
        display.append("TYPE: ").append(report.getReportType().getDisplayName()).append("\n");
        display.append("GENERATED: ").append(report.getFormattedDate()).append("\n");
        display.append("=".repeat(80)).append("\n\n");
        display.append(report.getData());

        if (report.getSummary() != null && !report.getSummary().isEmpty()) {
            display.append("\n").append("=".repeat(80)).append("\n");
            display.append("SUMMARY:\n");
            display.append(report.getSummary());
        }

        reportArea.setText(display.toString());
        reportArea.setCaretPosition(0);
    }

    private void printReport() {
        if (reportArea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No report to print",
                    "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            boolean complete = reportArea.print();
            if (complete) {
                statusLabel.setText("Report sent to printer");
            } else {
                statusLabel.setText("Printing cancelled");
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(this,
                    "Error printing report: " + e.getMessage(),
                    "Print Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exportReport() {
        if (reportArea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No report to export",
                    "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Export Report");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);

        // Add file filters
        fileChooser.addChoosableFileFilter(new FileFilter() {
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".txt");
            }

            public String getDescription() {
                return "Text Files (*.txt)";
            }
        });

        fileChooser.addChoosableFileFilter(new FileFilter() {
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".csv");
            }

            public String getDescription() {
                return "CSV Files (*.csv)";
            }
        });

        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String filterDesc = fileChooser.getFileFilter().getDescription();

            // Add extension if not present
            if (filterDesc.contains("*.txt") && !file.getName().toLowerCase().endsWith(".txt")) {
                file = new File(file.getAbsolutePath() + ".txt");
            } else if (filterDesc.contains("*.csv") && !file.getName().toLowerCase().endsWith(".csv")) {
                file = new File(file.getAbsolutePath() + ".csv");
            }

            // Check if file exists
            if (file.exists()) {
                int confirm = JOptionPane.showConfirmDialog(this,
                        "File already exists. Overwrite?",
                        "Confirm Overwrite",
                        JOptionPane.YES_NO_OPTION);
                if (confirm != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            try (FileWriter writer = new FileWriter(file)) {
                writer.write(reportArea.getText());
                statusLabel.setText("Report exported to: " + file.getName());
                JOptionPane.showMessageDialog(this,
                        "Report exported successfully!",
                        "Export Complete", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this,
                        "Error exporting report: " + e.getMessage(),
                        "Export Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void saveCurrentReport() {
        if (reportArea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No report to save",
                    "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String title = JOptionPane.showInputDialog(this,
                "Enter report title:",
                "Save Report",
                JOptionPane.QUESTION_MESSAGE);

        if (title == null || title.trim().isEmpty()) {
            return;
        }

        InventoryReportType type = (InventoryReportType) reportTypeCombo.getSelectedItem();

        try {
            // Extract data from displayed report
            String displayText = reportArea.getText();
            int dataStart = displayText.indexOf("=".repeat(80)) + 82;
            String data = dataStart < displayText.length() ?
                    displayText.substring(dataStart) : displayText;

            Report report = reportGenerator.generateCustomReport(
                    title.trim(), data, type, currentUserId, currentUserName);

            statusLabel.setText("Report saved with ID: " + report.getReportId());
            loadSavedReports();

            JOptionPane.showMessageDialog(this,
                    "Report saved successfully!",
                    "Save Complete", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error saving report: " + e.getMessage(),
                    "Save Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadSavedReports() {
        try {
            List<Report> reports = reportGenerator.getAllReports();
            tableModel.setRowCount(0);

            for (Report report : reports) {
                tableModel.addRow(new Object[]{
                        report.getReportId(),
                        report.getTitle(),
                        report.getReportType().getDisplayName(),
                        report.getShortDate()
                });
            }

            statusLabel.setText("Loaded " + reports.size() + " saved reports");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error loading reports: " + e.getMessage(),
                    "Load Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadSelectedReport() {
        int selectedRow = reportsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this,
                    "Please select a report to load",
                    "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int reportId = (int) tableModel.getValueAt(selectedRow, 0);

        try {
            Report report = reportGenerator.getReportById(reportId);
            if (report != null) {
                // Update report type combo
                reportTypeCombo.setSelectedItem(report.getReportType());

                // Display the report
                displayReport(report);
                statusLabel.setText("Loaded report: " + report.getTitle());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error loading report: " + e.getMessage(),
                    "Load Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteSelectedReport() {
        int selectedRow = reportsTable.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }

        int reportId = (int) tableModel.getValueAt(selectedRow, 0);
        String reportTitle = (String) tableModel.getValueAt(selectedRow, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
            "Delete report: " + reportTitle + "?\nThis action cannot be undone.",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                boolean deleted = reportGenerator.deleteReport(reportId);
                if (deleted) {
                    loadSavedReports();
                    reportArea.setText("");
                    statusLabel.setText("Report deleted: " + reportTitle);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error deleting report: " + e.getMessage(),
                        "Delete Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // Progress dialog for long operations
    private static class ProgressDialog extends JDialog {
        private JProgressBar progressBar;

        public ProgressDialog(Frame parent, String message) {
            super(parent, "Please Wait", true);

            setLayout(new BorderLayout(10, 10));
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

            JLabel label = new JLabel(message, SwingConstants.CENTER);
            label.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));

            progressBar = new JProgressBar();
            progressBar.setIndeterminate(true);

            add(label, BorderLayout.CENTER);
            add(progressBar, BorderLayout.SOUTH);

            pack();
            setLocationRelativeTo(parent);
        }
    }

    // Quick report generation methods for dashboard
    public void quickGenerateInventorySummary() {
        reportTypeCombo.setSelectedItem(InventoryReportType.INVENTORY_SUMMARY);
        generateReport();
    }

    public void quickGenerateLowStockReport() {
        reportTypeCombo.setSelectedItem(InventoryReportType.LOW_STOCK);
        generateReport();
    }

    public void quickGenerateDailySalesReport() {
        reportTypeCombo.setSelectedItem(InventoryReportType.SALES_REPORT);
        startDateField.setValue(LocalDate.now());
        endDateField.setValue(LocalDate.now());
        generateReport();
    }

    // Get current report as text
    public String getCurrentReportText() {
        return reportArea.getText();
    }

    // Clear current report
    public void clearReport() {
        reportArea.setText("");
        statusLabel.setText("Ready");
    }
}