package report;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

public class ReportConfig {
    private static final String CONFIG_FILE = "report_config.properties";
    private Properties properties;
    
    public ReportConfig() {
        properties = new Properties();
        loadConfig();
    }
    
    private void loadConfig() {
        try (FileInputStream fis = new FileInputStream(CONFIG_FILE)) {
            properties.load(fis);
        } catch (IOException e) {
            // Create default config
            setDefaults();
            saveConfig();
        }
    }
    
    private void setDefaults() {
        // SRS 3.1: Performance requirements
        properties.setProperty("report.timeout.seconds", "10");
        properties.setProperty("search.timeout.seconds", "5");
        properties.setProperty("update.timeout.seconds", "3");
        
        // SRS 1.6: Exit summary
        properties.setProperty("show.exit.summary", "true");
        properties.setProperty("auto.save.reports", "true");
        
        // Report settings
        properties.setProperty("default.report.type", "INVENTORY_SUMMARY");
        properties.setProperty("auto.generate.daily", "false");
        properties.setProperty("email.reports", "false");
        
        // Format settings
        properties.setProperty("date.format", "yyyy-MM-dd");
        properties.setProperty("time.format", "HH:mm:ss");
        properties.setProperty("currency.symbol", "$");
        
        // Display settings
        properties.setProperty("font.size", "12");
        properties.setProperty("font.family", "Monospaced");
        properties.setProperty("max.rows.per.page", "50");
    }
    
    public void saveConfig() {
        try (FileOutputStream fos = new FileOutputStream(CONFIG_FILE)) {
            properties.store(fos, "Report Configuration");
        } catch (IOException e) {
            System.err.println("Error saving report config: " + e.getMessage());
        }
    }
    
    // Getters for configuration values
    public int getReportTimeout() {
        return Integer.parseInt(properties.getProperty("report.timeout.seconds", "10"));
    }
    
    public int getSearchTimeout() {
        return Integer.parseInt(properties.getProperty("search.timeout.seconds", "5"));
    }
    
    public int getUpdateTimeout() {
        return Integer.parseInt(properties.getProperty("update.timeout.seconds", "3"));
    }
    
    public boolean shouldShowExitSummary() {
        return Boolean.parseBoolean(properties.getProperty("show.exit.summary", "true"));
    }
    
    public boolean shouldAutoSaveReports() {
        return Boolean.parseBoolean(properties.getProperty("auto.save.reports", "true"));
    }
    
    public String getDefaultReportType() {
        return properties.getProperty("default.report.type", "INVENTORY_SUMMARY");
    }
    
    public boolean shouldAutoGenerateDaily() {
        return Boolean.parseBoolean(properties.getProperty("auto.generate.daily", "false"));
    }
    
    public boolean shouldEmailReports() {
        return Boolean.parseBoolean(properties.getProperty("email.reports", "false"));
    }
    
    // Setters
    public void setShowExitSummary(boolean show) {
        properties.setProperty("show.exit.summary", String.valueOf(show));
        saveConfig();
    }
    
    public void setAutoSaveReports(boolean autoSave) {
        properties.setProperty("auto.save.reports", String.valueOf(autoSave));
        saveConfig();
    }
    
    public void setDefaultReportType(String type) {
        properties.setProperty("default.report.type", type);
        saveConfig();
    }
}