import java.time.LocalDate;

public class Report {
    private int reportId;
    private InventoryReportType reportType;
    private LocalDate generatedDate;
    private int generatedBy;
    private String data;
    
    // SRS 1.6: Track inventory management and product trends
    public Report(int reportId, InventoryReportType reportType, LocalDate generatedDate, int generatedBy, String data) {
        this.reportId = reportId;
        this.reportType = reportType;
        this.generatedDate = generatedDate;
        this.generatedBy = generatedBy;
        this.data = data;
    }
    
    // SRS 1.6: Print summary table functionality
    public String printReport() {
        System.out.println("=== Report ID: " + reportId + " ===");
        System.out.println("Type: " + reportType);
        System.out.println("Generated: " + generatedDate);
        System.out.println("Generated By: " + generatedBy);
        System.out.println("Data:");
        System.out.println(data);
        System.out.println("=======================");
        return data;
    }
    
    // Getters and setters
    public int getReportId() { return reportId; }
    public void setReportId(int reportId) { this.reportId = reportId; }
    
    public InventoryReportType getReportType() { return reportType; }
    public void setReportType(InventoryReportType reportType) { this.reportType = reportType; }
    
    public LocalDate getGeneratedDate() { return generatedDate; }
    public void setGeneratedDate(LocalDate generatedDate) { this.generatedDate = generatedDate; }
    
    public int getGeneratedBy() { return generatedBy; }
    public void setGeneratedBy(int generatedBy) { this.generatedBy = generatedBy; }
    
    public String getData() { return data; }
    public void setData(String data) { this.data = data; }
}